# Generated by Django 6.0.4 on 2026-04-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studyrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyRequest',
        ),
    ]
